# services:
#   - type: web
#     name: trackingapp-backend
#     env: node
#     region: frankfurt
#     plan: free
#     buildCommand: cd backend && yarn install --frozen-lockfile && yarn build
#     startCommand: cd backend && yarn deploy-db && yarn serve
#     healthCheckPath: /
#     # domains:
#     #   - api.clubmaster.io
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: cryptoExchange
#           property: connectionString

  # - type: web
  #   name: exchange-frontend
  #   env: static
  #   region: frankfurt
  #   plan: free
  #   buildCommand: cd frontend && yarn install --frozen-lockfile && yarn build
  #   staticPublishPath: ./frontend/build
  #   # domains:
  #   #   - clubmaster.io
  #   envVars:
  #     - key: nodeBackendUrl
  #       fromService:
  #         name: exchange-backend
  #         type: web
  #         envVarKey: RENDER_EXTERNAL_URL
  #   routes:
  #     - type: rewrite
  #       source: /*
  #       destination: /index.html

# databases:
#   - name: luksodatabase
#     region: frankfurt
#     plan: free